### ISSUE TITLE
Add capability to read from zip compressed SAFE files

### ISSUE THREAD

**Issue by gillins** [ubarsc/python-fmask#23]
**[Original report](https://bitbucket.org/chchrsc/python-fmask/issue/23) by Johan Mollevik (Bitbucket: [Johan Mollevik](https://bitbucket.org/Johan Mollevik), ).**

----------------------------------------

Hi

Now that the SAFE format is suported an added feature would be support for reading directly from zip compressed SAFE archives. This is something which several graphical GIS programs does quite happily (SNAP and QGIS for example) and from my knowledge of the zip format should be quite doable. 

The gain for doing this would be space savings at the processing machine and simplified processing as the zip files are whats downloaded from ESA.

Thanks a lot for maintaining this for the comunity

**Comment by neilflood** [comment]
Just for the record, I think I never got back to this because the additional work of reading not just the images but also the XML files etc., from the zipped SAFE file, but only for the case of Sentinel-2, seemed more trouble than it was worth. Unzipping the archive is not really a serious hurdle. I would reconsider if anyone made a good case, though.
