### ISSUE TITLE
Output file are colored with one colour

### ISSUE THREAD

**Issue by janceviciusjulius** [ubarsc/python-fmask#53]
I am trying to run f-mask algorith with this simple demo code:
![image](https://user-images.githubusercontent.com/64422065/158811167-1201d512-bf64-496f-9fca-fc156342a112.png)

and I got this result:
![image](https://user-images.githubusercontent.com/64422065/158811230-2bc937cb-f194-4dbe-be1f-e840965f4db0.png)

while .SAFE folder which I use looks:
![image](https://user-images.githubusercontent.com/64422065/158811309-a5ddb1d1-ffcf-4d85-87d0-128ba66192d9.png)

Can you help me solve this problem?

Thank You. Looking forward to hearing from you

**Comment by neilflood** [comment]
I don't know exactly what is going on there. However, since this image is from around 55 degrees north, in winter, it may be an example of a known problem with low sun angles. There is some discussion of it here #11. 

As mentioned there, it may need some adjustment of the thresholds. The first one to play with would be `--cloudprobthreshold`, which you could increase to 50 (as suggested in the discussion), and then try a few different values to see what works best. 

The other two thresholds which might be relevant are related to the snow calculations, `--nirsnowthreshold` and `--greensnowthreshold`. As suggested in the older discussion, they could be increased to 0.3, and see what happens.
